Repository subhadeeproy3902/BloxAI, pull requests merged in 2024-06, with the labels that each got.

#161 Bug #156 , profile page ,sidebar responsive and Overflow issue is fix
  src/app/dashboard/_components/SideNav.tsx
  src/app/dashboard/archive/_components/Navbar.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/profile/_components/TeamList.tsx
  src/app/dashboard/profile/page.tsx
Labels: bug, gssoc, level1

#169 feat : login loader
  convex/files.tsx
  src/app/dashboard/_components/SideNav.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/dashboard/archive/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/profile/page.tsx
  src/components/shared/Loader.tsx
Labels: gssoc, level2

#168 Fix for issue #162: Getting started page when already logged in else …
  src/components/shared/Header.tsx
Labels: bug, gssoc, level1

#175 Files
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/dashboard/profile/_components/TeamList.tsx
  src/app/dashboard/profile/page.tsx
Labels: gssoc, level3

#176 Cancel button
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/teams/create/page.tsx
  src/app/workspace/[fileId]/page.tsx
Labels: gssoc, level3

#178 Fixing the typos issue
  CONTRIBUTING.md
  src/app/contact/page.tsx
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/app/page.tsx
  src/components/shared/Creators.tsx
  src/components/shared/FollowingCard.tsx
Labels: gssoc, level1

#183 Delete team
  convex/teams.tsx
  src/app/dashboard/_components/SideNav.tsx
  src/app/dashboard/_components/SideNavBottomSection.tsx
Labels: gssoc, level2

#184 Fixed Responsiveness of Sidebar
  src/app/contributors/ContributorsData.ts
  src/app/dashboard/_components/SideNav.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/components/shared/FollowingCard.tsx
  src/components/shared/Hero.tsx
  src/components/shared/StartNow.tsx
  src/components/shared/TooltipSection.tsx
Labels: gssoc, level1

#189 feat: AI UI
  package.json
  src/app/workspace/_components/WorkspaceHeader.tsx
  src/components/shared/AiModal.tsx
  src/components/ui/checkbox.tsx
Labels: gssoc, level3

#190 Update README.md
  README.md
Labels: gssoc, level1

#192 Adding the feature to scroll Up
  src/app/page.tsx
  src/components/shared/ScrollUp.tsx
Labels: gssoc, level1

#198 AI - Documentation design
  .env.example
  src/app/workspace/[fileId]/page.tsx
  src/app/workspace/_components/Editor.tsx
  src/app/workspace/_components/WorkspaceHeader.tsx
  src/components/shared/AiModal.tsx
  src/config/gemini.ts
Labels: gssoc, level3

#202 automatically closes the side nav bar for small screens
  src/app/dashboard/_components/SideNav.tsx
Labels: gssoc, level1

#203 fix: markdown bug
  package.json
  src/app/workspace/_components/Editor.tsx
  src/components/shared/AiModal.tsx
  src/config/gemini.ts
Labels: gssoc, level3

#204 feat: AI-excalidraw
  package.json
  src/app/workspace/_components/Canvas.tsx
  src/components/shared/AiModal.tsx
  src/components/ui/tooltip.tsx
Labels: gssoc, level3

#207 Responsive
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/profile/_components/FileList.tsx
Labels: gssoc, level3

#208 fixed a slight problem with dark mode theme
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/profile/_components/FileList.tsx
Labels: bug, gssoc, level1

#215 feat: collab ui
  public/insta.svg
  public/linkedin.svg
  public/twitter.svg
  public/whatsapp.svg
  src/app/dashboard/page.tsx
  src/components/shared/InviteModal.tsx
  src/components/shared/JoinTeamForm.tsx
  src/components/shared/JoinTeamModal.tsx
Labels: gssoc, level3

#218 feat: Dashboard Navbar
  src/app/dashboard/page.tsx
  src/components/shared/InviteModal.tsx
  src/components/shared/JoinTeamModal.tsx
Labels: gssoc, level3

#219 feat: coolab api
  convex/teams.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/dashboard/layout.tsx
  src/app/teams/create/page.tsx
Labels: gssoc, level3

#223 feat: Toast
  src/components/shared/AiModal.tsx
  src/components/shared/InviteModal.tsx
  src/components/shared/JoinTeamModal.tsx
Labels: gssoc, level3

#226 feat: toast
  convex/teams.tsx
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/profile/_components/FileList.tsx
  src/app/teams/create/page.tsx
Labels: gssoc, level3

#227 Fix: Issue#225 - Added Code of conduct page
  src/app/codeofconduct/page.tsx
  src/components/shared/CodeOfConduct.tsx
  src/components/shared/Footer.tsx
Labels: gssoc, level3

#238 feat: link UI
  public/teamInvite.svg
  src/app/invite/[id]/page.tsx
  src/components/shared/AiModal.tsx
  src/components/shared/InviteModal.tsx
  src/components/shared/TermsDiv.tsx
Labels: gssoc, level3

#241 Issue#228 fixed. Improved the UI of the contact form.
  .env.example
  src/app/globals.css
  src/components/shared/Footer.tsx
  src/components/shared/contactform.tsx
Labels: gssoc, level3

#243 fix: card responsive
  src/app/dashboard/_components/FileList.tsx
Labels: gssoc, level2

#244 feat: collab working
  convex/teams.tsx
  src/app/dashboard/page.tsx
  src/app/invite/[id]/page.tsx
  src/components/shared/JoinTeamForm.tsx
  src/components/shared/JoinTeamModal.tsx
Labels: gssoc, level3

#248 Fix collab
  src/app/invite/[id]/page.tsx
  src/components/shared/JoinTeamForm.tsx
Labels: gssoc, level2

#253 fix: getAll api
  convex/teams.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
Labels: gssoc, level2

#255 feat: rename api
  convex/files.tsx
  src/components/shared/JoinTeamForm.tsx
Labels: gssoc, level3

#262 feat: rename api
  convex/teams.tsx
Labels: gssoc, level2

#269 feat: rename file functionality
  convex/teams.tsx
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/components/shared/RenameFileForm.tsx
  src/components/shared/RenameFileModal.tsx
  src/components/shared/RenameTeamForm.tsx
Labels: gssoc, level3

#275 Automatically Comment on Pull Requests
  .github/workflows/autocomment-pr-raise.yml
  src/app/contributors/ContributorsData.ts
Labels: gssoc, level1

#280 fix: bugs
  src/app/dashboard/_components/SideNav.tsx
  src/app/dashboard/layout.tsx
  src/app/invite/[id]/page.tsx
  src/components/shared/RenameFileModal.tsx
  src/components/shared/RenameTeamModal.tsx
Labels: gssoc, level2

#281 added scroll to top features in contibutor and review us section
  src/app/contributors/page.tsx
  src/app/review/page.tsx
Labels: gssoc, level1

#284 added in contact us page
  src/app/contact/page.tsx
Labels: gssoc, level1

#283 Created Working Review form
  .env.example
  package.json
  src/components/shared/customerreviews.tsx
Labels: gssoc, level2

#289 Added the Getting Started page
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/app/gettingstarted/page.tsx
Labels: gssoc, level3

#292 About us
  public/doodle.png
  src/app/aboutus/Typewriter.tsx
  src/app/aboutus/features/Lottie.tsx
  src/app/aboutus/features/page.tsx
  src/app/aboutus/page.tsx
  src/components/shared/Footer.tsx
  src/components/shared/Header.tsx
Labels: gssoc, level3

#285 reviews to mail
  package.json
  src/app/features/Lottie.tsx
  src/app/features/page.tsx
  src/components/shared/customerreviews.tsx
Labels: gssoc, level1

#295 feat: settings UI
  package.json
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/app/dashboard/settings/_components/Navbar.tsx
  src/app/dashboard/settings/_components/SettingsForm.tsx
  src/app/dashboard/settings/page.tsx
  src/app/globals.css
  src/components/ui/avatar.tsx
Labels: gssoc, level3

#297 feat: authorized access
  src/app/invite/[id]/page.tsx
Labels: gssoc, level2

#298 feat: setiings
  src/app/dashboard/settings/_components/SettingsForm.tsx
  src/app/dashboard/settings/page.tsx
Labels: gssoc, level2

#301 feat: Send email integration added using resend
  .env.example
  package.json
  src/app/api/mail/route.ts
  src/app/contributors/ContributorsData.ts
  src/components/shared/InviteModal.tsx
  src/components/ui/EmailForm.tsx
Labels: gssoc, level3

#300 feat: dynamic images
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/profile/_components/UserImage.tsx
  src/app/dashboard/profile/page.tsx
Labels: gssoc, level3

#306 created a good looking log in page
  public/login.png
  src/app/dashboard/layout.tsx
Labels: gssoc, level2

#308 Feedback form
  src/app/contributors/ContributorsData.ts
  src/components/shared/customerreviews.tsx
Labels: gssoc, level1

#313 auto commenting feature added for issue raised
  .github/workflows/autocommetn-iss-raised.yml
  src/app/contributors/ContributorsData.ts
Labels: gssoc, level1

#316 sign up route fixed
  src/app/dashboard/layout.tsx
Labels: gssoc, level1

#317 refactor: replace redundant <a> tag with <span>
  src/app/dashboard/layout.tsx
Labels: gssoc, level1

#319 feat: 404 not found page added with config
  src/app/[...not_found]/page.ts
  src/app/not-found.tsx
Labels: gssoc, level2

#334 [Bug] : `Nav bar` mismatch color fixed
  src/app/contributors/ContributorsData.ts
  src/app/dashboard/_components/SideNav.tsx
Labels: gssoc, level1

#337 Getting started ui changes
  src/app/gettingstarted/page.tsx
Labels: gssoc, level1

#340 Review us sectio UI - Scrolling
  src/app/globals.css
  src/components/shared/customerreviews.tsx
  src/components/ui/reviewcarousel.tsx
  tailwind.config.ts
Labels: gssoc, level3

#341 Solved issue 362
  src/components/shared/Header.tsx
Labels: gssoc, level1

#342 Feat/304
  convex/teams.tsx
  convex/user.tsx
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
Labels: gssoc, level2

#343 feat: team members ui
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/components/shared/MembersList.tsx
Labels: gssoc, level3

#346 made review us scrolling responsive to small screens
  src/components/ui/reviewcarousel.tsx
Labels: gssoc, level1

#347 Overflow issue in features section
  src/app/aboutus/features/page.tsx
Labels: gssoc, level1

#349 feat: modal team members
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/components/shared/MemberModal.tsx
  src/components/shared/MembersList.tsx
Labels: gssoc, level3

#358 feat: api for private and public
  .env.example
  convex/files.tsx
  package.json
  src/app/api/files/private/route.ts
  src/app/api/files/public/route.ts
  src/app/api/teams/get/route.ts
  src/app/dashboard/_components/FileList.tsx
  src/config/AxiosInstance.ts
Labels: gssoc, level3

#359 save as pdf option added
  next.config.mjs
  package.json
  src/app/workspace/[fileId]/page.tsx
  src/app/workspace/_components/Canvas.tsx
  src/app/workspace/_components/Editor.tsx
  src/app/workspace/_components/WorkspaceHeader.tsx
Labels: gssoc, level3

#361 feat: UI for private and public file
  src/app/api/files/private/route.ts
  src/app/api/files/public/route.ts
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/archive/page.tsx
  src/app/dashboard/page.tsx
  src/components/shared/FileStatusModal.tsx
  src/components/ui/badge.tsx
  src/lib/API-URLs.ts
Labels: gssoc, level3

#363 feat/356
  src/app/workspace/[fileId]/page.tsx
  src/components/shared/FileStatusModal.tsx
Labels: gssoc, level2

#367 feat: read and write api
  convex/files.tsx
  convex/schemas.ts
  src/app/api/files/read/route.ts
  src/app/api/files/write/route.ts
  src/app/api/teams/get/route.ts
Labels: gssoc, level3

#368 fixed the pdf flowchart issue
  src/app/workspace/[fileId]/page.tsx
Labels: gssoc, level2

#374 fix: create file api
  convex/files.tsx
  convex/schemas.ts
  src/app/api/files/read/route.ts
  src/components/shared/MemberModal.tsx
Labels: gssoc, level2
