Repository subhadeeproy3902/BloxAI, pull requests merged in 2024-05, with the labels that each got.

#122 added workflow as mentioned in issue #119
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc, level1

#127 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: gssoc, level2

#128 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: gssoc, level2

#121 added workflow as mentioned in issue #116
  .github/workflows/autocomment-pr-merge.yml
Labels: gssoc, level1

#134 Update README.md
  README.md
Labels: gssoc, level2

#142 fixes for workflow failure
  .github/workflows/autocomment-iss-close.yml
  .github/workflows/autocomment-pr-merge.yml
Labels: bug, gssoc, level1

#148 Added a Privacy Policy page
  package.json
  pnpm-lock.yaml
  src/app/contributors/ContributorsData.ts
  src/app/privacy/page.tsx
  src/components/shared/Footer.tsx
  src/components/shared/PrivacyPolicy.tsx
Labels: gssoc, level3

#151 feat: user profile
  src/app/dashboard/page.tsx
  src/app/dashboard/profile/_components/FileList.tsx
  src/app/dashboard/profile/_components/TeamList.tsx
  src/app/dashboard/profile/_components/UserImage.tsx
  src/app/dashboard/profile/page.tsx
Labels: gssoc, level3

#152 fix: profile
  src/app/dashboard/profile/_components/FileList.tsx
  src/app/dashboard/profile/_components/TeamList.tsx
Labels: gssoc, level1

#144 feat: archive feature
  convex/files.tsx
  src/app/contributors/ContributorsData.ts
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/app/dashboard/archive/_components/Navbar.tsx
  src/app/dashboard/archive/page.tsx
  src/app/dashboard/page.tsx
Labels: gssoc, level3

#157 Fix for issue #143: Client Side Rendering
  src/app/contributors/ContributorsData.ts
  src/app/dashboard/_components/SideNavTopSection.tsx
Labels: gssoc, level2

#160 feat: team-slice
  src/app/Redux/Team/team-slice.tsx
  src/app/dashboard/_components/SideNav.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/dashboard/archive/page.tsx
  src/app/store.tsx
Labels: gssoc, level2
