Repository subhadeeproy3902/BloxAI, pull requests merged in 2024-07, with the labels that each got.

#386 Feat/384
  src/app/api/teams/members/[id]/route.ts
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/components/shared/DeleteTeamMember.tsx
  src/components/shared/MemberCarousel.tsx
  src/lib/API-URLs.ts
Labels: gssoc, level3

#391 feat/390
  src/app/dashboard/team/_components/FileList.tsx
  src/app/dashboard/team/page.tsx
  src/components/shared/MemberCarousel.tsx
Labels: gssoc, level2

#400 Feat/399
  convex/files.tsx
  src/app/api/files/read/route.ts
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/dashboard/team/_components/FileList.tsx
  src/components/shared/ReadAccessModal.tsx
  src/lib/API-URLs.ts
Labels: gssoc, level3

#401 feat:remove validators
  convex/files.tsx
Labels: gssoc, level1

#402 feat: Read functionality working
  src/app/api/files/read/route.ts
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/app/dashboard/team/page.tsx
  src/app/teams/settings/[id]/page.tsx
  src/app/teams/settings/_components/FileList.tsx
  src/components/shared/MemberModal.tsx
  src/components/shared/ReadAccessModal.tsx
Labels: gssoc, level3

#408 feat/407
  src/app/workspace/[fileId]/page.tsx
  src/app/workspace/_components/Editor.tsx
  src/components/shared/PrivateAlert.tsx
  src/components/shared/WriteAccessModal.tsx
Labels: gssoc, level3

#410 fix: responsiveness of user settings
  src/app/dashboard/settings/_components/SettingsForm.tsx
  src/app/dashboard/settings/page.tsx
Labels: gssoc, level1

#412 Enhance README.md
  README.md
  public/Gssoc Label.png
Labels: gssoc, level1

#416 Created a Dynamic Contributors page
  src/app/contributors/ContributorsData.ts
  src/app/contributors/page.tsx
  src/components/shared/Contributors.tsx
Labels: gssoc, level2

#417 Feat/414
  package.json
  public/google.svg
  src/app/change/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/shared/SigninForm.tsx
  src/components/shared/SignupForm.tsx
Labels: gssoc, level2

#424 Version: Added a version page with cards and dates to keep the users updated about the changes and new features of BloxAI
  src/app/globals.css
  src/app/version/page.tsx
  src/app/version/version.tsx
  src/app/version/versionData.ts
Labels: gssoc, level3

#425 feat: nextauth and mongodb
  package.json
  src/app/SessionProvider.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/[kindeAuth]/route.ts
  src/app/api/auth/register/route.ts
  src/app/dashboard/layout.tsx
  src/app/layout.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/shared/Header.tsx
  src/components/shared/SigninForm.tsx
  src/components/shared/SignupForm.tsx
  src/lib/API-URLs.ts
  src/lib/MongoDB.ts
  src/models/user.ts
Labels: gssoc, level3

#427 Feat/426
  .env.example
  middleware.ts
  package.json
  src/app/Redux/Auth/auth-slice.ts
  src/app/SessionProvider.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/app/dashboard/_components/SideNav.tsx
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/dashboard/archive/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/profile/page.tsx
  src/app/dashboard/settings/page.tsx
  src/app/invite/[id]/page.tsx
  src/app/layout.tsx
  src/app/signin/page.tsx
  src/app/store.tsx
  src/app/teams/create/page.tsx
  src/app/workspace/[fileId]/page.tsx
  src/components/shared/ReadAccessModal.tsx
  src/components/shared/SigninForm.tsx
  src/components/shared/SignupForm.tsx
  src/components/shared/WriteAccessModal.tsx
  src/models/user.ts
  src/types/next-auth.d.ts
  src/types/testimonial.ts
  src/types/types.d.ts
Labels: gssoc, level3

#431 fix: build issues
  src/app/layout.tsx
  src/app/signin/page.tsx
  src/app/workspace/_components/Editor.tsx
Labels: bug, gssoc, level1

#432 fix: redux persistence
  package.json
  src/app/Provider.tsx
  src/app/Redux/Auth/auth-slice.ts
  src/app/Redux/Menu/menuSlice.ts
  src/app/Redux/Team/team-slice.ts
  src/app/ReduxProviders.tsx
  src/app/dashboard/_components/SideNav.tsx
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/dashboard/archive/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/profile/page.tsx
  src/app/dashboard/settings/page.tsx
  src/app/invite/[id]/page.tsx
  src/app/layout.tsx
  src/app/signin/page.tsx
  src/app/store.tsx
  src/app/teams/create/page.tsx
  src/app/workspace/[fileId]/page.tsx
  src/components/shared/DeleteTeamMember.tsx
  src/components/shared/FileStatusModal.tsx
  src/components/shared/InviteModal.tsx
  src/components/shared/MemberModal.tsx
  src/components/shared/ReadAccessModal.tsx
  src/components/shared/RenameTeamForm.tsx
  src/components/shared/SigninForm.tsx
  src/components/shared/SignupForm.tsx
  src/components/shared/WriteAccessModal.tsx
  src/config/store.ts
Labels: gssoc, level3

#435 Fixed the navbar for the tablet screen size 768px
  src/components/shared/Header.tsx
Labels: gssoc, level1

#436 Added Preloader
  package.json
  src/app/layout.tsx
  src/components/shared/Preloader.tsx
  src/components/shared/custom.d.ts
  src/components/ui/Preloader.json
Labels: gssoc, level2

#443 feat: scheams
  src/models/file.ts
  src/models/team.ts
Labels: gssoc, level2

#447 feat: toast
  src/app/api/auth/[...nextauth]/options.ts
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/signin/page.tsx
  src/components/shared/SigninForm.tsx
Labels: gssoc, level1

#449 feat: middleware
  middleware.ts
Labels: gssoc, level2

#438 added the navigation in topbar footer to version
  src/app/version/page.tsx
  src/components/shared/Footer.tsx
  src/components/shared/Header.tsx
Labels: gssoc, level1

#450 Api/445
  src/Middleware/AuthMiddleware.ts
  src/app/api/files/create/route.ts
  src/app/api/files/private/route.ts
  src/app/api/health/route.ts
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/config/AxiosInstance.ts
  src/config/AxiosProtectedRoute.ts
  src/lib/API-URLs.ts
  src/models/file.ts
  src/models/user.ts
  src/types/types.d.ts
Labels: gssoc, level3

#454 Fixed "Scroll to Top" Button Visibility in Light and Dark Modes
  src/components/shared/ScrollUp.tsx
Labels: gssoc, level1

#456 feat: create new file api integration
  src/app/teams/create/page.tsx
  src/components/shared/SignupForm.tsx
  src/lib/API-URLs.ts
Labels: gssoc, level2

#455 Design Dedicated "Licensing" Page Reflecting "MIT License"
  src/app/licensing/page.tsx
  src/components/shared/Footer.tsx
  src/components/shared/licensing.tsx
Labels: gssoc, level1

#464 Feat/462
  src/app/api/files/private/route.ts
  src/app/api/files/public/route.ts
  src/app/api/files/update/route.ts
  src/app/dashboard/_components/FileList.tsx
  src/components/shared/FileStatusModal.tsx
  src/components/shared/RenameFileForm.tsx
  src/components/shared/RenameFileModal.tsx
  src/lib/API-URLs.ts
Labels: gssoc, level3

#470 Feat/468
  src/app/api/files/delete/[id]/route.ts
  src/app/api/teams/delete/[id]/route.ts
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/lib/API-URLs.ts
Labels: gssoc, level3

#477 feat: profile page
  src/app/api/files/create/route.ts
  src/app/api/files/getAllFiles/[userId]/route.ts
  src/app/api/teams/create/route.ts
  src/app/dashboard/_components/FileList.tsx
  src/app/dashboard/_components/SideNavBottomSection.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/profile/_components/FileList.tsx
  src/app/dashboard/profile/_components/TeamList.tsx
  src/app/dashboard/profile/page.tsx
  src/app/workspace/[fileId]/page.tsx
  src/app/workspace/_components/Canvas.tsx
  src/app/workspace/_components/Editor.tsx
  src/components/shared/FileStatusModal.tsx
  src/components/shared/RenameFileForm.tsx
  src/components/shared/RenameFileModal.tsx
  src/lib/API-URLs.ts
  src/models/team.ts
  src/types/types.d.ts
Labels: gssoc, level3

#476 Added the changed icons
  src/components/shared/Footer.tsx
Labels: gssoc, level1

#478 Fixed Connect with us elements miss alignment in Contact Us page
  src/components/shared/contactform.tsx
Labels: gssoc, level1

#484 feat: profile and dashboard
  src/app/Redux/Auth/auth-slice.ts
  src/app/api/dashboard/public/save/route.ts
  src/app/api/dashboard/save/route.ts
  src/app/api/files/getFileById/[id]/route.ts
  src/app/api/files/update/route.ts
  src/app/api/user/update/route.ts
  src/app/dashboard/settings/_components/SettingsForm.tsx
  src/app/dashboard/settings/page.tsx
  src/app/workspace/[fileId]/page.tsx
  src/app/workspace/_components/Canvas.tsx
  src/app/workspace/_components/Editor.tsx
  src/lib/API-URLs.ts
  src/models/file.ts
Labels: gssoc, level3

#486 feat/485
  src/app/api/teams/getTeamById/[id]/route.ts
  src/app/api/teams/member/route.ts
  src/app/dashboard/_components/SideNav.tsx
  src/app/dashboard/_components/SideNavTopSection.tsx
  src/app/invite/[id]/page.tsx
  src/components/shared/JoinTeamForm.tsx
  src/lib/API-URLs.ts
Labels: gssoc, level3

#487 Issue Combine the pages as sections in 1 page. #482 fixed
  src/app/aboutus/Typewriter.tsx
  src/app/aboutus/features/Lottie.tsx
  src/app/aboutus/features/page.tsx
  src/app/aboutus/page.tsx
  src/app/contact/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/review/page.tsx
  src/components/shared/About.tsx
  src/components/shared/Features.tsx
  src/components/shared/Header.tsx
  src/components/shared/TooltipSection.tsx
  src/components/shared/contactform.tsx
  src/components/shared/customerreviews.tsx
  src/components/ui/animation1.json
  src/components/ui/animation2.json
  src/components/ui/animation3.json
  src/components/ui/animation4.json
  src/components/ui/animation5.json
  src/components/ui/animation6.json
Labels: gssoc, level3

#489 Added styling foor active nav element
  src/components/shared/Header.tsx
Labels: gssoc, level1

#490 Issue#483 fixed. Added the changelog page
  src/app/version/page.tsx
  src/app/version/version.tsx
  src/app/version/versionData.ts
  src/components/shared/Version.tsx
  tailwind.config.ts
Labels: gssoc, level3

#493 Fix/editorjs
  src/app/api/auth/[...nextauth]/options.ts
  src/app/dashboard/layout.tsx
  src/app/signin/page.tsx
  src/app/workspace/_components/Editor.tsx
  src/components/shared/SigninForm.tsx
  src/components/shared/SignupForm.tsx
Labels: gssoc, level2
